# Use Node.js LTS version (consider a stable version that aligns with `canvas` requirements, e.g., 18.x)
FROM node:20.17
# Install necessary packages for Puppeteer
RUN apt-get update && apt-get install -y \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxcomposite1 \
    libxrandr2 \
    libxdamage1 \
    libxfixes3 \
    libpango1.0-0 \
    libgbm-dev \
    libasound2 \
    libgtk-3-0 \
    libdrm2 \
    libxcb-dri3-0 \
    libxshmfence1 \
    ca-certificates \
    fonts-liberation \
    gconf-service \
    libappindicator1 \
    libappindicator3-1 \
    lsb-release \
    xdg-utils \
    wget \
    libcairo2-dev \
    libjpeg-dev \
    libgif-dev \
    pkg-config \
    build-essential \
    g++ \
    libpangocairo-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

